version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate:latest
    container_name: migrations
    command:
      - -path
      - /migrations
      - -database
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      - up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations

  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./config:/usr/local/src/config
    environment:
      - CONFIG_PATH=${CONFIG_PATH}

volumes:
  pgdata:
