app:
  name: "feline-intelligence"
  version: "1.0.0"
  env: "local" # Possible values: local, dev, prod

server:
  host: "127.0.0.1"
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s

logger:
  level: "debug" # Possible levels: debug, info, warn, error
  format: "text"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "feline_db"
  sslmode: "disable"